# Generated by Django 5.2.4 on 2025-07-30 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0002_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='requires_prescription',
            field=models.BooleanField(default=False),
        ),
    ]
