# Generated by Django 5.2.4 on 2025-07-30 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0004_prescription_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pharmacy.order'),
        ),
    ]
