# Generated by Django 5.2.4 on 2025-07-30 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pharmacy", "0005_prescription_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="delivery_method",
            field=models.CharField(default="delivery", max_length=20),
        ),
        migrations.AddField(
            model_name="order",
            name="payment_method",
            field=models.CharField(default="cod", max_length=20),
        ),
    ]
