# Generated by Django 5.2.4 on 2025-07-30 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0006_order_delivery_method_order_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='cart_data',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prescription',
            name='delivery_method',
            field=models.CharField(default='delivery', max_length=20),
        ),
        migrations.AddField(
            model_name='prescription',
            name='payment_method',
            field=models.CharField(default='cod', max_length=20),
        ),
    ]
